version: "3.7"
services:
  database:
    image: postgres:12.7
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ticketbookingdb
      POSTGRES_USER: ticketbookinguser
      POSTGRES_PASSWORD: AToughPassword!
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env.docker
    depends_on:
      - database
    networks:
      - default
    volumes:
      - ./db/migrations:/db/migrations
    ports:
      - "8080:8080"
volumes:
  dbdata:
